package com.suneee.smf.smf.model;

import java.util.Date;

public class Testerpmy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.data1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private Integer data1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.data2
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private Integer data2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.data3
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private Integer data3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.data4
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private Integer data4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.datax
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private String datax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.create_time
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.create_time1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private String createTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.create_time2
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private Integer createTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testerp1.daten
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    private Date daten;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.data1
     *
     * @return the value of testerp1.data1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public Integer getData1() {
        return data1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.data1
     *
     * @param data1 the value for testerp1.data1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setData1(Integer data1) {
        this.data1 = data1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.data2
     *
     * @return the value of testerp1.data2
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public Integer getData2() {
        return data2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.data2
     *
     * @param data2 the value for testerp1.data2
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setData2(Integer data2) {
        this.data2 = data2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.data3
     *
     * @return the value of testerp1.data3
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public Integer getData3() {
        return data3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.data3
     *
     * @param data3 the value for testerp1.data3
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setData3(Integer data3) {
        this.data3 = data3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.data4
     *
     * @return the value of testerp1.data4
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public Integer getData4() {
        return data4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.data4
     *
     * @param data4 the value for testerp1.data4
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setData4(Integer data4) {
        this.data4 = data4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.datax
     *
     * @return the value of testerp1.datax
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public String getDatax() {
        return datax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.datax
     *
     * @param datax the value for testerp1.datax
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setDatax(String datax) {
        this.datax = datax == null ? null : datax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.create_time
     *
     * @return the value of testerp1.create_time
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.create_time
     *
     * @param createTime the value for testerp1.create_time
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.create_time1
     *
     * @return the value of testerp1.create_time1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public String getCreateTime1() {
        return createTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.create_time1
     *
     * @param createTime1 the value for testerp1.create_time1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setCreateTime1(String createTime1) {
        this.createTime1 = createTime1 == null ? null : createTime1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.create_time2
     *
     * @return the value of testerp1.create_time2
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public Integer getCreateTime2() {
        return createTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.create_time2
     *
     * @param createTime2 the value for testerp1.create_time2
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setCreateTime2(Integer createTime2) {
        this.createTime2 = createTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testerp1.daten
     *
     * @return the value of testerp1.daten
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public Date getDaten() {
        return daten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testerp1.daten
     *
     * @param daten the value for testerp1.daten
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    public void setDaten(Date daten) {
        this.daten = daten;
    }
}