package com.suneee.smf.smf.dao;

import com.suneee.smf.smf.model.Testerpmy;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;


@Repository  
@Transactional
public interface TesterpmyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testerp1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    int deleteByPrimaryKey(Integer data1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testerp1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    int insert(Testerpmy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testerp1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    int insertSelective(Testerpmy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testerp1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    Testerpmy selectByPrimaryKey(Integer data1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testerp1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    int updateByPrimaryKeySelective(Testerpmy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testerp1
     *
     * @mbggenerated Fri Jan 20 10:56:06 CST 2017
     */
    int updateByPrimaryKey(Testerpmy record);
    
    /**
     * my demo for testing
     * @return List<Testerpmy>
     */
    List<Testerpmy> selectAll();
    
    /**
     * my test for select by any other SQL
     * @return List
     */
    List superManagerSelect(String sql);
}